In [1]:
from aocd import get_data, submit
# from aocd.get import current_day

from IPython.display import display
from IPython.core.display import Markdown

current_day is only available in December (EST)


In [2]:
DAY = 8
YEAR = 2022

In [3]:
url = f"https://adventofcode.com/{YEAR}/day/{DAY}"
display(Markdown(f"#### See [{YEAR} Day {DAY}]({url})."))

#### See [2022 Day 8](https://adventofcode.com/2022/day/8).

In [4]:
data = get_data(year=YEAR, day=DAY)

In [7]:
data.splitlines()[:5]

['222112212213012301211134200002032424301142102231553514443201341400212230204230401120330131220022210',
 '102112111222233101031402012403201222213455312422432144422311112420034421043440034112120031011001111',
 '102122223023130331231203443334122242323322135341452245355543411453442102413422113120120032330210022',
 '110001231100011332234413013213045445233212225343233154553335222544334133331211032334110100233102201',
 '112120312023213203233203304022134355314211535351534544145442243315233432344112114414123111203320020']

# Part A

In [59]:
import numpy as np
forest = np.array([list(l) for l in data.splitlines()]).astype(int)
forest

array([[2, 2, 2, ..., 2, 1, 0],
       [1, 0, 2, ..., 1, 1, 1],
       [1, 0, 2, ..., 0, 2, 2],
       ...,
       [2, 0, 1, ..., 1, 1, 1],
       [2, 0, 2, ..., 0, 2, 2],
       [2, 1, 0, ..., 0, 1, 1]])

In [35]:
visible = np.zeros_like(forest)

n_row, n_col = forest.shape

for r in range(n_row):
    max_height = -1
    for c in range(n_col):
        if forest[r,c] > max_height:
            visible[r,c] = 1
            max_height = forest[r,c]

    max_height = -1
    for c in reversed(range(n_col)):
        if forest[r,c] > max_height:
            visible[r,c] = 1
            max_height = forest[r,c]

for c in range(n_col):
    max_height = -1
    for r in range(n_row):
        if forest[r,c] > max_height:
            visible[r,c] = 1
            max_height = forest[r,c]

    max_height = -1
    for r in reversed(range(n_row)):
        if forest[r,c] > max_height:
            visible[r,c] = 1
            max_height = forest[r,c]

visible

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 0, 1, ..., 0, 0, 1],
       [1, 0, 1, ..., 0, 1, 1],
       ...,
       [1, 0, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [37]:
n_visible = np.sum(visible)
n_visible

1798

In [38]:
submit(n_visible, year=YEAR, day=DAY)

answer a: None
submitting for part a
coerced int64 value 1798 for 2022/08


That's the right answer!  You are one gold star closer to collecting enough star fruit. [Continue to Part Two]


# Part B

In [58]:
# forest = np.array(
#     [[3,0,3,7,3],
# [2,5,5,1,2],
# [6,5,3,3,2],
# [3,3,5,4,9],
# [3,5,3,9,0],]
# )
# forest

In [62]:
scenic_score = np.zeros_like(forest)

n_row, n_col = forest.shape

for r in range(n_row):
    for c in range(n_col):
        h = forest[r,c]

        left = 0
        for i in range(1,n_col):
            if c-i < 0:
                break
            left += 1
            if forest[r,c-i] >= h:
                break

        right = 0
        for i in range(1,n_col):
            if c+i >= n_col:
                break
            right += 1
            if forest[r,c+i] >= h:
                break

        up = 0
        for i in range(1,n_row):
            if r-i < 0:
                break
            up += 1
            if forest[r-i,c] >= h:
                break

        down = 0
        for i in range(1,n_row):
            if r+i >= n_row:
                break
            down += 1
            if forest[r+i,c] >= h:
                break

        scenic_score[r,c] = left * right * up * down
scenic_score

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  1,  6, ...,  2,  1,  0],
       [ 0,  1,  8, ...,  1, 16,  0],
       ...,
       [ 0,  1,  2, ..., 16,  2,  0],
       [ 0,  1, 32, ...,  1,  9,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [63]:
best = np.max(scenic_score)

In [64]:
submit(best, year=YEAR, day=DAY)

answer a: 1798
submitting for part b (part a is already completed)
coerced int64 value 259308 for 2022/08


That's the right answer!  You are one gold star closer to collecting enough star fruit.You have completed Day 8! You can [Shareon
  Twitter
Mastodon] this victory or [Return to Your Advent Calendar].
